### ISSUE TITLE
Polymer 1.0 elements ?

### ISSUE THREAD

**Issue by abourget** [MediaMath/strand#13]
We've ported all our apps to 1.0 .. is there a roadmap for you guys to port to 1.0 as well ?

**Comment by dlasky** [comment]
We had some straggling .5 components/features to get out the door first, but 1.0 port is starting this week.

**Comment by Nevraeka** [comment]
@dlasky will this be a big bang update or will components be pulled out and updated one by one?

**Comment by dlasky** [comment]
@Nevraeka we are still sorting the build tooling around that, my original intention was keep the work in a 1.0 branch but the actual release would be tagged 2.0.0 for semver. 

That said, if we are going to get some additional bug surface area out of doing smaller or one off releases I am definitely open to that approach, but less sure on the appropriate versioning schema.

**Comment by Nevraeka** [comment]
@dlasky it's definitely not a clear cut decision. The Polymer team still gets tons of bugs to the library for issues that are really related to a specific component. Many who haven't seen the evolution of the elements expect that when the library updates, all of the elements will too. A branch might be a better approach. Still not easy though. Either way, the performance in 1.0 vs. 0.5 is night & day. It will be worth it for sure. Good luck

**Comment by nazar-pc** [comment]
@dlasky, when 1.0-based elements expected to be ready?

**Comment by dlasky** [comment]
Ideally september, but given some of the bugs we are finding in the template implementation in 1.0 it may be a bit longer as we may have some dependencies on fixes from google.
