### ISSUE TITLE
Issues with DatePicker Example Using IE 10 and IE 11

### ISSUE THREAD

**Issue by zawarski** [MediaMath/strand#83]
Would really like to use Strand but when I try to "close" the DatePicker example (http://mediamath.github.io/strand/mm-datepicker.html) using IE 10 or IE 11, "Unable to get property 'close' of undefined or null reference" error is displayed in debugging console for IE 10 and IE 11. Don't know if this is caused by something in the demo page for the component, or the component itself.

**Comment by dlasky** [comment]
so ie 10 isn't supported by polymer itself.

it looks like in 11 the behaviors that it depends on are undefined for some reason. 

edge is fine

**Comment by zawarski** [comment]
In mm-datepicker.js, line 367, it calls BehaviorUtils.findSuper(StrandTraits.PositionablePanel, 'close'). The structure of the StrandTraits.PositionablePanel, when using Chrome, has the expected 'close'. When using IE11, the structure of the object is very different, and the expected 'close' content does not exist.

**Comment by dlasky** [comment]
4.0.3 this appears to be resolved in IE11. Unable to test in 10.

**Comment by zawarski** [comment]
Works great in ie11 now. Thanks!
