### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by gedw99** [MediaMath/strand#98]
It's great to see this. I use polymer components and I noticed that many are similar to the Google ones.

So if in the readme you can explain why it would clear up this question for me and others I expect.

The sync aspect looks nice btw. Will try it out

**Comment by dlasky** [comment]
google's components didnt exist at the inception of this project.

additionally their design is mobile first which presents problems in some cases

**Comment by gedw99** [comment]
make sense thanks.
